name: Build and Commit Embed Code

on:
  pull_request:
    branches: [ embed-code-go ]

concurrency:
  group: building
  cancel-in-progress: true

jobs:

  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.1'

    - name: List pre-build directory
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd ./embed-code-go/bin
        ls -l *

    - name: Remove File
      uses: JesseTG/rm@v1.0.3
      with:
        path: ./bin/embed_code_${{ matrix.os }}
        
    - name: Build embed_code.go
      run: |
        cd ./embed-code-go/
        go build -o ./bin/embed_code_${{ matrix.os }} ./embed_code.go

    - name: List post-build directory
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd ./embed-code-go/bin
        ls -l *
        
    - name: Commit built files
      uses: EndBug/add-and-commit@v9
      with:
        add: './embed-code-go/bin/embed_code_${{ matrix.os }} --force'
        message: 'Build embed_code.go for ${{ matrix.os }}'
        default_author: github_actions
