name: Tests for Go

on:
  pull_request:
    branches:
      - embed-code-go


jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./embed-code-go/
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'

      - name: Run tests
        # Needs to have "-p 1" argument to run tests sequentially. It's because the tests
        # create temporary files which can cause issues.  
        run: go test -v ./... -p 1
