name: Tests on Ubuntu

on:
  pull_request:
    branches:
      - embed-code-go

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'

      - name: Run tests
        run: |
          cd ./embed-code-go/
          go test -v ./...
